version: '3'

services:
    app: &default
        build: .
        image: phansar/app
        volumes:
            - .:/app
            - ./.cache:/cache

    check_format:
        <<: *default
        environment:
            CMAKE_BUILD_TYPE: Debug
        command: >
            sh -c "pipenv install &&
                   rm -rf build &&
                   cmake -S /app -B build -DENABLE_CMAKE_FORMAT=ON -DENABLE_BLACK=ON -DENABLE_CLANG_FORMAT=ON -DENABLE_CLANG_TIDY=ON &&
                   cmake --build build --target check-format-cmake-format &&
                   cmake --build build --target check-format-black &&
                   cmake --build build --target check-format-clang-format &&
                   cmake --build build --target check-format-clang-tidy &&
                   rm -rf build"

    gcc_debug_test: &gcc_build_test
        <<: *default
        environment:
            CMAKE_BUILD_TYPE: Debug
            CMAKE_C_COMPILER: gcc
            CMAKE_CXX_COMPILER: g++
        command: >
            sh -c "pipenv install &&
                   rm -rf build &&
                   ccache -z &&
                   cmake -S /app -B build &&
                   cmake --build build &&
                   ctest --ctest-dir build --output-on-failure --timeout 30 &&
                   rm -rf build &&
                   ccache -sx"

    gcc_release_test:
        <<: *gcc_build_test
        environment:
            CMAKE_BUILD_TYPE: Release

    gcc_relwithdebinfo_test:
        <<: *gcc_build_test
        environment:
            CMAKE_BUILD_TYPE: RelWithDebInfo

    gcc_minsizerel_test:
        <<: *gcc_build_test
        environment:
            CMAKE_BUILD_TYPE: MinSizeRel

    clang_debug_test: &clang_build_test
        <<: *gcc_build_test
        environment:
            CMAKE_BUILD_TYPE: Debug
            CMAKE_C_COMPILER: clang
            CMAKE_CXX_COMPILER: clang++

    clang_release_test:
        <<: *clang_build_test
        environment:
            CMAKE_BUILD_TYPE: Release

    clang_relwithdebinfo_test:
        <<: *clang_build_test
        environment:
            CMAKE_BUILD_TYPE: RelWithDebInfo

    clang_minsizerel_test:
        <<: *clang_build_test
        environment:
            CMAKE_BUILD_TYPE: MinSizeRel
