version: '3'

services:
    app: &default
        build: .
        image: phansar/app
        environment: &default_environment
            CMAKE_C_COMPILER: ${CMAKE_C_COMPILER:-gcc}
            CMAKE_CXX_COMPILER: ${CMAKE_C_COMPILER:-g++}
        volumes:
            - .:/app
            - ./.cache:/cache

    check_format:
        <<: *default
        environment:
            <<: *default_environment
            CMAKE_BUILD_TYPE: Debug
        command: >
            sh -c "pipenv install &&
                   rm -rf build &&
                   cmake -S /app -B build -DENABLE_CMAKE_FORMAT=ON -DENABLE_BLACK=ON -DENABLE_CLANG_FORMAT=ON -DENABLE_CLANG_TIDY=ON &&
                   cmake --build build --target check-format-cmake-format &&
                   cmake --build build --target check-format-black &&
                   cmake --build build --target check-format-clang-format &&
                   cmake --build build --target check-format-clang-tidy &&
                   rm -rf build"

    debug_test: &build_test
        <<: *default
        environment:
            <<: *default_environment
            CMAKE_BUILD_TYPE: Debug
        command: >
            sh -c "pipenv install &&
                   rm -rf build &&
                   ccache -z &&
                   cmake -S /app -B build &&
                   cmake --build build &&
                   ctest --ctest-dir build --output-on-failure --timeout 30 &&
                   rm -rf build &&
                   ccache -sx"

    release_test:
        <<: *build_test
        environment:
            <<: *default_environment
            CMAKE_BUILD_TYPE: Release

    relwithdebinfo_test:
        <<: *build_test
        environment:
            <<: *default_environment
            CMAKE_BUILD_TYPE: RelWithDebInfo

    minsizerel_test:
        <<: *build_test
        environment:
            <<: *default_environment
            CMAKE_BUILD_TYPE: MinSizeRel
