#ifndef LIBCOMMON_MACROS_INCLUDE_COMMON_MACROS_EXPECT_HPP
#define LIBCOMMON_MACROS_INCLUDE_COMMON_MACROS_EXPECT_HPP

#include <plibsys.h>

#define EXPECT_TRUE P_LIKELY
#define EXPECT_FALSE P_UNLIKELY

#endif
