#ifndef LIBCOMMON_MACROS_INCLUDE_PH_COMMON_MACROS_EXPECT_HPP
#define LIBCOMMON_MACROS_INCLUDE_PH_COMMON_MACROS_EXPECT_HPP

#include <plibsys.h>

#define PH_EXPECT_TRUE P_LIKELY
#define PH_EXPECT_FALSE P_UNLIKELY

#endif
