name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: Set up system
          run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt install -y wget build-essential cmake gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9
            wget "http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
            tar xf clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
            sudo cp -R ./clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04/* /usr/local
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7
            sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
            mkdir build
        - name: Check code formatting
          working-directory: ./utils
          run: |
            ./check-clang-format.sh
        - name: Check include guards
          working-directory: ./utils
          run: |
            ./check-include-guards.sh
        - name: Build and test (debug)
          working-directory: ./build
          run: |
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make -j2
            ctest --timeout 30 -V
        - name: Clean build directory
          working-directory: ./build
          run: |
            rm -rf *
        - name: Build and test (release)
          working-directory: ./build
          run: |
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j2
            ctest --timeout 30 -V
