name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
        name: ${{ matrix.name }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                name: [gcc, clang]

                include:
                    - name: gcc
                      cc: gcc
                      cxx: g++

                    - name: clang
                      cc: clang
                      cxx: clang++
        env:
            CC: ${{ matrix.cc }}
            CXX: ${{ matrix.cxx }}

        steps:
        - uses: actions/checkout@v2

        - uses: actions/cache@v2
          with:
            path: |
                ${{ github.workspace }}/.cache
            key: ${{ runner.os }}-${{ matrix.name }}-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-${{ matrix.name }}-
                ${{ runner.os }}-

        - name: Build container
          run: |
              docker-compose build

        - name: Check formatting
          run: |
              docker-compose run check_format

        - name: Build and test Debug
          run: |
              docker-compose run debug_test

        - name: Build and test Release
          run: |
              docker-compose run release_test

        - name: Build and test RelWithDebInfo
          run: |
              docker-compose run relwithdebinfo_test

        - name: Build and test MinSizeRel
          run: |
              docker-compose run minsizerel_test
