name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - name: Set up system
          run: |
            sudo apt update
            sudo apt install build-essential cmake libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
            mkdir build
        - name: Build and test (debug)
          working-directory: ./build
          run: |
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make -j2
            make test
        - name: Clean build directory
          working-directory: ./build
          run: |
            rm -rf *
        - name: Build and test (release)
          working-directory: ./build
          run: |
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j2
            make test
