name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
        name: ${{ matrix.compiler }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                compiler: [gcc, clang]

        steps:
        - uses: actions/checkout@v2

        - uses: actions/cache@v2
          with:
            path: |
                ${{ github.workspace }}/.cache
            key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-${{ matrix.compiler }}-
                ${{ runner.os }}-

        - name: Build container
          shell: bash
          run: |
              docker-compose build

        - name: Check formatting
          shell: bash
          run: |
              docker-compose run check_format

        - name: Build and test Debug
          shell: bash
          run: |
              docker-compose run ${{ matrix.compiler }}_debug_test

        - name: Build and test Release
          shell: bash
          run: |
              docker-compose run ${{ matrix.compiler }}_release_test

        - name: Build and test RelWithDebInfo
          shell: bash
          run: |
              docker-compose run ${{ matrix.compiler }}_relwithdebinfo_test

        - name: Build and test MinSizeRel
          shell: bash
          run: |
              docker-compose run ${{ matrix.compiler }}_minsizerel_test
