name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
        name: Continuous Integration
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - uses: actions/cache@v2
          with:
            path: |
                ${{ github.workspace }}/.cache
            key: ${{ runner.os }}-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-

        - name: Build container
          shell: bash
          run: |
              docker-compose build

        - name: Check formatting
          shell: bash
          run: |
              docker-compose run check_format

        - name: Build and test Debug
          shell: bash
          run: |
              docker-compose run debug_test

        - name: Build and test Release
          shell: bash
          run: |
              docker-compose run release_test

        - name: Build and test RelWithDebInfo
          shell: bash
          run: |
              docker-compose run relwithdebinfo_test

        - name: Build and test MinSizeRel
          shell: bash
          run: |
              docker-compose run minsizerel_test
